[package]
name = "vectordb-gateway"
description = "HTTP/JSON REST gateway for VectorDB"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vectordb-gateway"
path = "src/main.rs"

[dependencies]
vectordb-client.workspace = true
vectordb-proto.workspace = true
vectordb-auth.workspace = true

anyhow.workspace = true
axum.workspace = true
axum-server.workspace = true
clap.workspace = true
lazy_static.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
