[package]
name = "vectordb-client"
description = "Rust client SDK for VectorDB"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vectordb-proto.workspace = true
vectordb-auth.workspace = true
vectordb-rbac.workspace = true
anyhow.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
