#!/usr/bin/env python3
"""
VectorDB cluster lifecycle.

One generator that owns docker-compose.yml AND all per-replica TOML configs.
Drives `up`, `scale-rf`, `add-shard`, `down`, etc. so the user never has to
hand-edit compose files or per-replica peer lists.

State is persisted in `.cluster.state.json` at the repo root, so subsequent
commands know the current shape:

    {"shards": 2, "rf": 3}

Volume naming matches the previous RF=3 stack (`vdb_s<S>_r<R>`), so an
existing cluster's data is preserved across the migration.

Examples
--------

    # First-time bring-up: 1 shard, RF=1
    ./scripts/cluster.py up

    # 2 shards, RF=3 (production-like)
    ./scripts/cluster.py up --rf 3 --shards 2

    # Bump RF on a running cluster (new replicas auto-bootstrap from peers)
    ./scripts/cluster.py scale-rf --rf 5

    # Add capacity (auto-rebalance moves data to the new shard)
    ./scripts/cluster.py add-shard

    # Stop everything (volumes preserved)
    ./scripts/cluster.py down
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPOSE = ROOT / "docker-compose.yml"
CONFIG_DIR = ROOT / "config" / "cluster"
STATE = ROOT / ".cluster.state.json"

GENERATED_HEADER = (
    "# AUTO-GENERATED by scripts/cluster.py — DO NOT EDIT BY HAND.\n"
    "# Regenerate with `./scripts/cluster.py up --rf N --shards M`.\n"
    "# State of record: .cluster.state.json\n"
)


def raft_id(shard: int, replica: int) -> int:
    """Stable Raft node id, scoped per-shard so RF can grow without collisions."""
    return shard * 100 + replica


def load_state() -> dict:
    if STATE.exists():
        try:
            return json.loads(STATE.read_text())
        except json.JSONDecodeError:
            pass
    return {"shards": 1, "rf": 1}


def save_state(state: dict) -> None:
    STATE.write_text(json.dumps(state, indent=2) + "\n")


# ---------------------------------------------------------------------------
# Config rendering
# ---------------------------------------------------------------------------


def render_router_config(state: dict) -> str:
    shards = state["shards"]
    rf = state["rf"]
    nodes = []
    for s in range(shards):
        for r in range(1, rf + 1):
            nodes.append(
                "[[cluster.nodes]]\n"
                f'id = "shard-{s}-r{r}"\n'
                f'grpc = "http://shard-{s}-r{r}:6334"\n'
                f"shard_ids = [{s}]"
            )
    nodes_block = "\n\n".join(nodes)

    return (
        f"{GENERATED_HEADER}"
        "\n[server]\n"
        'listen = "0.0.0.0:6333"\n'
        "\n[cluster]\n"
        'node_id = "router"\n'
        'role = "router"\n'
        f"shard_count = {shards}\n"
        f'replication_factor = {rf}\n'
        f"\n{nodes_block}\n"
        "\n# Auto-rebalance: moves orphan points when shard_count changes\n"
        "[rebalance]\n"
        "enabled = true\n"
        "interval_secs = 60\n"
        "page_size = 256\n"
        "max_moves_per_sweep = 0\n"
        "idle_skip_after = 5\n"
        "\n# Dynamic topology / health probing — picks live Raft leader as primary\n"
        "[topology]\n"
        "health_interval_secs = 10\n"
        "config_reload_interval_secs = 30\n"
        "registration_ttl_secs = 90\n"
        "auto_shard_count = true\n"
    )


def render_replica_config(state: dict, s: int, r: int) -> str:
    shards = state["shards"]
    rf = state["rf"]
    peers_blocks = []
    for rp in range(1, rf + 1):
        peers_blocks.append(
            "[[raft.peers]]\n"
            f"id = {raft_id(s, rp)}\n"
            f'addr = "shard-{s}-r{rp}:7334"\n'
            f'grpc = "http://shard-{s}-r{rp}:6334"'
        )
    peers_block = "\n\n".join(peers_blocks)

    return (
        f"{GENERATED_HEADER}"
        "\n[server]\n"
        'listen = "0.0.0.0:6334"\n'
        "\n[storage]\n"
        'data_dir = "/data"\n'
        "sync_wal = true\n"
        "\n[cluster]\n"
        f'node_id = "shard-{s}-r{r}"\n'
        'role = "data"\n'
        f"shard_count = {shards}\n"
        f"shard_id = {s}\n"
        f"replication_factor = {rf}\n"
        'router_grpc = "http://router:6333"\n'
        "\n# Auto-snapshot every 5 minutes (compacts WAL, speeds future cold starts)\n"
        "[snapshot]\n"
        "interval_secs = 300\n"
        "compact_wal = true\n"
        "min_wal_entries = 100\n"
        "\n[raft]\n"
        f"node_id = {raft_id(s, r)}\n"
        'listen = "0.0.0.0:7334"\n'
        f'vector_endpoint = "http://shard-{s}-r{r}:6334"\n'
        "election_timeout_ms = 750\n"
        "heartbeat_interval_ms = 150\n"
        f"\n{peers_block}\n"
        "\n# Replica bootstrap: empty replica pulls historical state via Scroll RPC.\n"
        "# Raft InstallSnapshot supersedes this once peers are up — both are safe.\n"
        "# peer_retry_secs covers the case where new + sibling replicas cold-start\n"
        "# together: the sibling's gRPC isn't up during its WAL replay, so the new\n"
        "# replica retries with backoff for up to 10 min instead of giving up.\n"
        "[bootstrap]\n"
        "enabled = true\n"
        "page_size = 256\n"
        "bulk_chunk_size = 256\n"
        "max_total_secs = 3600\n"
        "peer_retry_secs = 600\n"
        "snapshot_after = true\n"
    )


# ---------------------------------------------------------------------------
# Compose rendering
# ---------------------------------------------------------------------------

DATA_TEMPLATE_HEADER = """x-data-template: &data-template
  build: .
  restart: unless-stopped
  environment:
    RUST_LOG: ${RUST_LOG:-info,vectordb=info}
  healthcheck:
    test: ["CMD", "vectordb", "--endpoint", "http://localhost:6334", "health"]
    interval: 5s
    timeout: 3s
    retries: 60
    # Allow up to 10 minutes for cold-start WAL replay on a node with a large
    # backlog. The container is marked "starting" — not "unhealthy" — for
    # this entire window.
    start_period: 600s
"""


def render_compose(state: dict) -> str:
    shards = state["shards"]
    rf = state["rf"]
    services = []
    depends = []

    for s in range(shards):
        for r in range(1, rf + 1):
            name = f"shard-{s}-r{r}"
            services.append(
                f"  {name}:\n"
                f"    <<: *data-template\n"
                f'    command: ["vectordb-server", "--config", "/etc/vectordb/node.toml"]\n'
                f"    volumes:\n"
                f"      - ./config/cluster/{name}.toml:/etc/vectordb/node.toml:ro\n"
                f"      - vdb_s{s}_r{r}:/data\n"
            )
            depends.append(f"      {name}: {{ condition: service_started }}")

    services_block = "\n".join(services)
    depends_block = "\n".join(depends)
    volumes_block = "\n".join(
        f"  vdb_s{s}_r{r}:" for s in range(shards) for r in range(1, rf + 1)
    )

    return (
        f"{GENERATED_HEADER}"
        f"# Topology: shards={shards}, rf={rf}\n"
        f"#\n"
        f"# Endpoints:\n"
        f"#   gateway HTTP : http://localhost:8080\n"
        f"#   admin UI     : http://localhost:8090\n"
        f"#   router gRPC  : localhost:6333\n"
        "\n"
        f"{DATA_TEMPLATE_HEADER}"
        "\nservices:\n"
        f"{services_block}"
        "\n  router:\n"
        "    build: .\n"
        "    restart: unless-stopped\n"
        '    command: ["vectordb-server", "--config", "/etc/vectordb/router.toml"]\n'
        "    volumes:\n"
        "      - ./config/cluster/router.toml:/etc/vectordb/router.toml:ro\n"
        "    ports:\n"
        '      - "6333:6333"\n'
        "    healthcheck:\n"
        '      test: ["CMD", "vectordb", "--endpoint", "http://localhost:6333", "health"]\n'
        "      interval: 5s\n"
        "      timeout: 3s\n"
        "      retries: 30\n"
        "      start_period: 30s\n"
        "    depends_on:\n"
        f"{depends_block}\n"
        "\n  gateway:\n"
        "    build: .\n"
        "    restart: unless-stopped\n"
        '    command: ["vectordb-gateway"]\n'
        "    environment:\n"
        "      VECTORDB_GRPC: http://router:6333\n"
        "      VECTORDB_HTTP: 0.0.0.0:8080\n"
        "    ports:\n"
        '      - "8080:8080"\n'
        "    healthcheck:\n"
        '      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health >/dev/null 2>&1 || exit 1"]\n'
        "      interval: 5s\n"
        "      timeout: 3s\n"
        "      retries: 30\n"
        "      start_period: 10s\n"
        "    depends_on:\n"
        "      router: { condition: service_healthy }\n"
        "\n  admin:\n"
        "    build:\n"
        "      context: .\n"
        "      dockerfile: admin/Dockerfile\n"
        "    restart: unless-stopped\n"
        "    environment:\n"
        "      VECTORDB_URL: http://gateway:8080\n"
        '      ADMIN_LISTEN: ":8090"\n'
        "      EMBED_DEFAULT_URL: http://host.docker.internal:1234/v1\n"
        "      EMBED_DEFAULT_MODEL: text-embedding-nomic-embed-text-v1.5\n"
        "    extra_hosts:\n"
        '      - "host.docker.internal:host-gateway"\n'
        "    ports:\n"
        '      - "8090:8090"\n'
        "    depends_on:\n"
        "      - gateway\n"
        "\nvolumes:\n"
        f"{volumes_block}\n"
    )


def render_all(state: dict) -> None:
    """Write compose file + every replica config + router config."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    # Wipe stale shard-*.toml so volumes never get a config that references
    # peers that no longer exist.
    for old in CONFIG_DIR.glob("shard-*.toml"):
        old.unlink()

    (CONFIG_DIR / "router.toml").write_text(render_router_config(state))
    for s in range(state["shards"]):
        for r in range(1, state["rf"] + 1):
            (CONFIG_DIR / f"shard-{s}-r{r}.toml").write_text(
                render_replica_config(state, s, r)
            )
    COMPOSE.write_text(render_compose(state))

    # On macOS external volumes (HFS+/exFAT), each write spawns a `._<name>`
    # AppleDouble sidecar with extended attributes. Docker BuildKit's context
    # sender stat()s every file before consulting .dockerignore, and chokes on
    # those sidecars with "failed to xattr ._foo: operation not permitted".
    # Strip xattrs from what we just wrote so the sidecar never gets created.
    if sys.platform == "darwin":
        targets = [str(COMPOSE), str(CONFIG_DIR)]
        subprocess.run(
            ["xattr", "-cr", *targets],
            check=False,
            stderr=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
        )

    print(
        f"  rendered: {COMPOSE.relative_to(ROOT)}, "
        f"{1 + state['shards'] * state['rf']} configs in "
        f"{CONFIG_DIR.relative_to(ROOT)}"
    )


# ---------------------------------------------------------------------------
# Docker compose driver
# ---------------------------------------------------------------------------


def run_compose(*args: str, check: bool = True) -> int:
    cmd = ["docker", "compose", "-f", str(COMPOSE), *args]
    print(f"+ {' '.join(cmd)}", flush=True)
    try:
        return subprocess.run(cmd, check=check).returncode
    except FileNotFoundError:
        print("ERROR: 'docker compose' not found — install Docker Desktop or compose plugin.", file=sys.stderr)
        sys.exit(1)


def clean_macos_artifacts() -> None:
    """Strip AppleDouble (._*) and .DS_Store files that break Docker's tar reader.

    On macOS external volumes (the project lives on /Volumes/...), every write
    to a file spawns a sibling `._<name>` file with the resource fork. Docker's
    tar packer chokes on these with `failed to xattr ._foo: operation not
    permitted`. Two-stage cleanup:

      1. `dot_clean -m .` — merges the resource fork into native xattrs of the
         real file, then removes the `._*` sidecar (more thorough than `rm`).
      2. find/delete — sweep up anything dot_clean missed.

    Important: call this AFTER writing files, not before, otherwise newly-
    written files spawn fresh sidecars by the time docker reads them.
    """
    if sys.platform == "darwin":
        subprocess.run(
            ["dot_clean", "-m", str(ROOT)],
            check=False,
            stderr=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
        )
    subprocess.run(
        ["find", str(ROOT), "-name", "._*", "-type", "f", "-delete"],
        check=False,
        stderr=subprocess.DEVNULL,
    )
    subprocess.run(
        ["find", str(ROOT), "-name", ".DS_Store", "-type", "f", "-delete"],
        check=False,
        stderr=subprocess.DEVNULL,
    )


def info(state: dict) -> None:
    width = 56
    s = state["shards"]
    rf = state["rf"]
    nodes = s * rf
    rows = [
        ("topology",  f"{s} shard(s) × RF={rf}"),
        ("data nodes", str(nodes)),
        ("admin",      "http://127.0.0.1:8090"),
        ("gateway",    "http://127.0.0.1:8080"),
        ("router gRPC", "127.0.0.1:6333"),
    ]
    print()
    print("  ┌" + "─" * width + "┐")
    title = " VectorDB cluster"
    print("  │" + title + " " * (width - len(title)) + "│")
    print("  ├" + "─" * width + "┤")
    for label, value in rows:
        line = f" {label:<11}: {value}"
        print("  │" + line + " " * (width - len(line)) + "│")
    print("  └" + "─" * width + "┘")
    print()
    print("  ./scripts/cluster.py logs           # tail all services")
    print("  ./scripts/cluster.py scale-rf RF=5  # bump replication factor")
    print("  ./scripts/cluster.py add-shard      # add capacity")
    print("  ./scripts/cluster.py down           # stop (keeps data)")
    print("  ./scripts/cluster.py nuke           # stop + delete volumes")
    print()


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------


def cmd_up(args) -> None:
    state = load_state()
    if args.rf is not None:
        state["rf"] = args.rf
    if args.shards is not None:
        state["shards"] = args.shards
    if state["rf"] < 1 or state["shards"] < 1:
        sys.exit("rf and shards must be >= 1")
    if state["rf"] > 99 or state["shards"] > 99:
        sys.exit("rf and shards must be <= 99 (raft id scheme)")
    save_state(state)
    render_all(state)
    clean_macos_artifacts()
    run_compose("up", "-d", "--build")
    info(state)


def cmd_scale_rf(args) -> None:
    state = load_state()
    new_rf = args.rf
    if new_rf < 1:
        sys.exit("rf must be >= 1")
    if new_rf == state["rf"]:
        print(f"already at RF={new_rf}, nothing to do")
        return
    direction = "up" if new_rf > state["rf"] else "down"
    print(f"scaling RF {state['rf']} → {new_rf} ({direction})")
    state["rf"] = new_rf
    save_state(state)
    render_all(state)
    clean_macos_artifacts()
    run_compose("up", "-d", "--build")
    if direction == "up":
        print(
            "  new replicas will pull historical state via Raft InstallSnapshot\n"
            "  or Scroll bootstrap on first boot — be patient on cold start."
        )
    else:
        print("  removed replicas: stop the volumes manually if you want to free disk")
    info(state)


def cmd_add_shard(args) -> None:
    state = load_state()
    state["shards"] += 1
    save_state(state)
    render_all(state)
    clean_macos_artifacts()
    print(f"adding shard {state['shards'] - 1} (now {state['shards']} shards)")
    run_compose("up", "-d", "--build")
    print(
        "  router auto-rebalance will scroll every collection and migrate\n"
        "  ~1/N of points to the new shard. Watch progress:\n"
        "    curl http://127.0.0.1:8080/v1/admin/rebalance/status"
    )
    info(state)


def cmd_down(args) -> None:
    if not COMPOSE.exists():
        print(f"no {COMPOSE.relative_to(ROOT)} found, nothing to stop")
        return
    run_compose("down", check=False)


def cmd_nuke(args) -> None:
    if not COMPOSE.exists():
        print(f"no {COMPOSE.relative_to(ROOT)} found, nothing to nuke")
        return
    run_compose("down", "-v", check=False)


def cmd_ps(args) -> None:
    if not COMPOSE.exists():
        print(f"no {COMPOSE.relative_to(ROOT)} found")
        return
    run_compose("ps", check=False)


def cmd_logs(args) -> None:
    if not COMPOSE.exists():
        print(f"no {COMPOSE.relative_to(ROOT)} found")
        return
    extra = ["--tail=100", "-f"]
    if args.service:
        extra.append(args.service)
    run_compose("logs", *extra, check=False)


def cmd_info(args) -> None:
    state = load_state()
    info(state)


def cmd_render(args) -> None:
    """Generate compose + configs without starting docker."""
    state = load_state()
    if args.rf is not None:
        state["rf"] = args.rf
    if args.shards is not None:
        state["shards"] = args.shards
    save_state(state)
    render_all(state)


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------


def main() -> None:
    p = argparse.ArgumentParser(
        prog="cluster.py",
        description="VectorDB cluster lifecycle (single source of truth).",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    up = sub.add_parser("up", help="Build + start the cluster (default RF=1, 1 shard)")
    up.add_argument("--rf", type=int)
    up.add_argument("--shards", type=int)
    up.set_defaults(func=cmd_up)

    sr = sub.add_parser("scale-rf", help="Change replication factor")
    sr.add_argument("--rf", type=int, required=True)
    sr.set_defaults(func=cmd_scale_rf)

    asd = sub.add_parser("add-shard", help="Add one new shard (capacity)")
    asd.set_defaults(func=cmd_add_shard)

    d = sub.add_parser("down", help="Stop everything (keeps volumes)")
    d.set_defaults(func=cmd_down)

    n = sub.add_parser("nuke", help="Stop + DELETE all data volumes")
    n.set_defaults(func=cmd_nuke)

    ps = sub.add_parser("ps", help="Show container status")
    ps.set_defaults(func=cmd_ps)

    lg = sub.add_parser("logs", help="Tail logs (optionally for one service)")
    lg.add_argument("service", nargs="?")
    lg.set_defaults(func=cmd_logs)

    inf = sub.add_parser("info", help="Print cluster URLs")
    inf.set_defaults(func=cmd_info)

    rd = sub.add_parser("render", help="Regenerate compose + configs without starting docker")
    rd.add_argument("--rf", type=int)
    rd.add_argument("--shards", type=int)
    rd.set_defaults(func=cmd_render)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
